<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Careers_amp extends CI_Controller {
  
	public function index() {
		$data	= array();

		$data['meta_title']			= 'Careers at Odessa';
		$data['meta_description']	= 'We’re Odessa. Our leading software platform is at the heart of some of the largest and most innovative companies in auto and equipment finance, helping them to thrive in business.';
		$data['meta_keywords']		= 'leasing software jobs';
		$data['meta_author']		= '8Guild';
		$job_lists					= $this->get_job_list();
		
		// Grouping the opening by Teams
		$lists		= array();
        $dept       = array();
        $deptstring = "";
        $loc        = array();
        $locstring  = "";
		//var_dump($job_lists['objects']);die;
        foreach ($job_lists['content'] as $item) {
		//var_dump($item['title']);die;
			$temp = $item;
			if(!empty($item['office']['country']) && !in_array($item['office']['country'], $loc))
                array_push($loc, $item['office']['country']);
				
            if(!empty($item['department']) && !in_array($item['department'], $dept))
                array_push($dept, $item['department']);
			
		}
		sort($loc);
        sort($dept);
		arsort($lists);

        foreach ($loc as $item){
            $locstring = $locstring."<li data-key='data-filter-location' data-value='".$item."'>".$item."</option>";
        }
		//var_dump($locstring);die;
        foreach ($dept as $item){
            $deptstring = $deptstring."<li data-key='data-filter-department' data-value='".$item."'>".$item."</option>";
        }

        $data['location_filter']	= $locstring;
        $data['department_list']	= $dept;
        $data['department_filter']	= $deptstring;
		$data['lists']				= $job_lists['content'];
		//	var_dump($data['lists']);die;
		$this->load->helper('url');
	
		$this->load->view( 'layouts/amp_pages/header.amp.html', $data );
		$this->load->view('pages/amp_pages/careers.amp.html', $data);
		$this->load->view( 'layouts/amp_pages/footer.amp.html', $data );
	}

	public function get_job_list(){
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		
		curl_setopt($ch, CURLOPT_URL, 'https://odessainc.skillate.com/api/postings?offset=0&limit=100000');
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
    		echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		//var_dump(json_decode($result, true)); die;
		return json_decode($result, true);
	}

	

}
